apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: phase4-db-secret
  namespace: phase4-demo
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:337227272890:secret:phase4/db-credentials-tojE9p"
        objectType: "secretsmanager"
        objectAlias: "db-credentials"
